LibraryApp/Controllers/AuthorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LibraryApp.Data;
using LibraryApp.Models;

namespace LibraryApp.Controllers
{
    public class AuthorsController : Controller
    {
        private readonly LibraryAppContext _context;

        public AuthorsController(LibraryAppContext context)
        {
            _context = context;
        }

        // GET: Authors
        public async Task<IActionResult> Index()
        {
            return View(await _context.Authors.ToListAsync());
        }

        // GET: Authors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _context.Authors
                .Include(a => a.BooksWritten)
                    .ThenInclude(b => b.Book)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.Id == id);
            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }

        // GET: Authors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Authors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName")] Author author)
        {
            if (ModelState.IsValid)
            {
                _context.Add(author);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }

        // GET: Authors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _context.Authors.FindAsync(id);
            if (author == null)
            {
                return NotFound();
            }
            return View(author);
        }

        // POST: Authors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName")] Author author)
        {
            if (id != author.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(author);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AuthorExists(author.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }

        // GET: Authors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _context.Authors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }

        // POST: Authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var author = await _context.Authors.FindAsync(id);
            _context.Authors.Remove(author);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AuthorExists(int id)
        {
            return _context.Authors.Any(e => e.Id == id);
        }
    }
}

LibraryApp/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LibraryApp.Data;
using LibraryApp.Models;
using LibraryApp.ViewModels;
using Microsoft.EntityFrameworkCore.Query;

namespace LibraryApp.Controllers
{
    public class BooksController : Controller
    {
        private readonly LibraryAppContext _context;

        public BooksController(LibraryAppContext context)
        {
            _context = context;
        }

        // GET: Books
        public async Task<IActionResult> Index(string searchTerm = null)
        {
            var books = GetAllBooksWithDetails()
                .AsNoTracking();

            if (!string.IsNullOrEmpty(searchTerm))
            {
                books = books.Where(b => b.Title.Contains(searchTerm));
                ViewData["SearchTerm"] = searchTerm;
            }

            return View(await books.ToListAsync());
        }

        private IQueryable<Book> GetAllBooksWithDetails()
        {
            return _context.Books
                .Include(b => b.BookAuthors)
                    .ThenInclude(ba => ba.Author)
                .Include(b => b.Genres)
                    .ThenInclude(g => g.Genre);
        }

        // GET: Books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await GetAllBooksWithDetails()
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: Books/Create
        public async Task<IActionResult> Create()
        {
            var createModel = await NewEditBookViewModel();
            return View(createModel);
        }

        // POST: Books/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EditBookViewModel model)
        {
            if (!ModelState.IsValid) return View(model);
            
            var book = new Book
            {
                Title = model.Title,
                BookAuthors =
                    new List<BookAuthor>(model.SelectedAuthors.Select(a => new BookAuthor
                        {AuthorId = a, BookId = model.Id})),
                Genres = new List<GenreEntry>(model.SelectedGenres.Select(g => new GenreEntry
                    {GenreName = g, BookId = model.Id}))
            };
            _context.Add(book);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }

        // GET: Books/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await GetAllBooksWithDetails()
                .AsNoTracking()
                .FirstOrDefaultAsync(b => b.Id == id);
            return View(await PopulateEditBookViewModel(book));
        }

        private async Task<EditBookViewModel> PopulateEditBookViewModel(Book book)
        {
            var authors = await _context.Authors
                .Select(a => new SelectListItem($"{a.FirstName} {a.LastName}", a.Id.ToString()))
                .ToListAsync();
            var model = new EditBookViewModel
            {
                Id = book.Id,
                Title = book.Title,
                AvailableAuthors = authors,
                SelectedAuthors = book.BookAuthors.Select(b => b.AuthorId).ToList(),
                AvailableGenres = await _context.Genres.Select(g => new SelectListItem(g.Name, g.Name)).ToListAsync(),
                SelectedGenres = book.Genres.Select(b => b.GenreName).ToList()
            };
            return model;
        }

        private async Task<EditBookViewModel> NewEditBookViewModel()
        {
            var authors = await _context.Authors
                .Select(a => new SelectListItem($"{a.FirstName} {a.LastName}", a.Id.ToString()))
                .ToListAsync();
            var model = new EditBookViewModel
            {
                AvailableAuthors = authors,
                AvailableGenres = await _context.Genres.Select(g => new SelectListItem(g.Name, g.Name)).ToListAsync(),
            };
            return model;
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditBookViewModel model)
        {
            var book = await GetAllBooksWithDetails().FirstOrDefaultAsync(b => b.Id == model.Id);
            if (book == null)
            {
                return NotFound();
            }
            try
            {
                if (ModelState.IsValid)
                {
                    book.Title = model.Title;
                    UpdateGenres(model.SelectedGenres, book);
                    UpdateAuthors(model.SelectedAuthors, book);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                
            }
            catch (DbUpdateException e)
            {
                //Log the error (uncomment ex variable name and write a log.)
                ModelState.AddModelError("", "Unable to save changes. " +
                                             "Try again, and if the problem persists, " +
                                             "see your system administrator."); 
                
            }
            return View(await PopulateEditBookViewModel(book));
        }

        private void UpdateAuthors(IEnumerable<int> authorIds, Book book)
        {
            var selectedAuthors = new HashSet<int>(authorIds);
            var bookAuthors = new HashSet<int>(book.BookAuthors.Select(b => b.AuthorId));
            foreach (var author in _context.Authors)
            {
                if (selectedAuthors.Contains(author.Id))
                {
                    if (!bookAuthors.Contains(author.Id))
                    {
                        book.BookAuthors.Add(new BookAuthor {AuthorId = author.Id, BookId = book.Id});
                    }
                }
                else
                {
                    if (!bookAuthors.Contains(author.Id)) continue;
                    var bookAuthor = book.BookAuthors.FirstOrDefault(b => b.AuthorId.Equals(author.Id));
                    book.BookAuthors.Remove(bookAuthor);
                }
            }
        }

        private void UpdateGenres(IEnumerable<string> genreNames, Book book)
        {
            var selectedGenres = new HashSet<string>(genreNames);
            var bookGenres = new HashSet<string>(book.Genres.Select(b => b.GenreName));
            foreach (var genre in _context.Genres)
            {
                if (selectedGenres.Contains(genre.Name))
                {
                    if (!bookGenres.Contains(genre.Name))
                    {
                        book.Genres.Add(new GenreEntry {GenreName = genre.Name, BookId = book.Id});
                    }
                }
                else
                {
                    if (!bookGenres.Contains(genre.Name)) continue;
                    var bookGenre = book.Genres.FirstOrDefault(b => b.GenreName.Equals(genre.Name));
                    book.Genres.Remove(bookGenre);
                }
            }
        }

        // GET: Books/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var book = await GetAllBooksWithDetails()
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var book = await _context.Books.FindAsync(id);
            _context.Books.Remove(book);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

LibraryApp/Controllers/GenresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LibraryApp.Data;
using LibraryApp.Models;

namespace LibraryApp.Controllers
{
    public class GenresController : Controller
    {
        private readonly LibraryAppContext _context;

        public GenresController(LibraryAppContext context)
        {
            _context = context;
        }

        // GET: Genres
        public async Task<IActionResult> Index()
        {
            return View(await _context.Genres.ToListAsync());
        }

        // GET: Genres/Details/5
        public async Task<IActionResult> Details(string name)
        {
            if (name == null)
            {
                return NotFound();
            }

            var genre = await _context.Genres
                .Include(g => g.GenreEntries)
                    .ThenInclude(g => g.Book)
                        .ThenInclude(b => b.BookAuthors)
                            .ThenInclude(a => a.Author)
                .FirstOrDefaultAsync(m => m.Name == name);
            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }

        // GET: Genres/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Genres/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name")] Genre genre)
        {
            if (ModelState.IsValid)
            {
                _context.Add(genre);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        // GET: Genres/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = await _context.Genres.FindAsync(id);
            if (genre == null)
            {
                return NotFound();
            }
            return View(genre);
        }

        // POST: Genres/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("Name")] Genre genre)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(genre);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GenreExists(genre.Name))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        // GET: Genres/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = await _context.Genres
                .FirstOrDefaultAsync(m => m.Name == id);
            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }

        // POST: Genres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var genre = await _context.Genres.FindAsync(id);
            _context.Genres.Remove(genre);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GenreExists(string id)
        {
            return _context.Genres.Any(e => e.Name == id);
        }
    }
}

LibraryApp/Views/Books/Create.cshtml
@model LibraryApp.ViewModels.EditBookViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Book</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <partial name="_BookForm" model="@Model" />
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LibraryApp/Views/Books/Delete.cshtml
@model LibraryApp.Models.Book

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <partial name="_BookDetails" model="@Model"/>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

LibraryApp/Views/Books/Details.cshtml
@model LibraryApp.Models.Book

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <partial name="_BookDetails" model="@Model"/>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

LibraryApp/Views/Books/Edit.cshtml
@model LibraryApp.ViewModels.EditBookViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Book</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <partial name="_BookForm" model="@Model"/>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LibraryApp/Views/Books/Index.cshtml
@model IEnumerable<LibraryApp.Models.Book>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create" class="btn btn-success"><i class="fas fa-plus"></i> Add Book</a>
</p>
<form asp-action="Index" method="get">
    <div class="form-group">
        <input type="text" name="searchTerm" placeholder="Search For Book" value="@ViewData["SearchTerm"]"/>
        <input type="submit" value="Search"/>
    </div>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BookAuthors)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genres)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id">@Html.DisplayFor(modelItem => item.Title)</a> |
                <a asp-action="Edit" asp-route-id="@item.Id"><i class="fas fa-pen"></i></a>
            </td>
            <td>
                <ul>
                    @foreach (var bookAuthor in item.BookAuthors)
                    {
                        <li>
                            <a asp-controller="Authors" asp-action="Details" asp-route-id="@bookAuthor.AuthorId">@bookAuthor.Author.FirstName @bookAuthor.Author.LastName</a>
                        </li>
                    }
                </ul>
            </td>
            <td>
                <ul>
                    @foreach (var genre in item.Genres)
                    {
                    <li><a asp-controller="Genres" asp-action="Details" asp-route-name="@genre.GenreName">@genre.GenreName</a></li>
                    }
                </ul>
            </td>
            <td>
                <a asp-action="Delete" asp-route-id="@item.Id" class="fas fa-trash"></a>
            </td>
        </tr>
}
    </tbody>
</table>

LibraryApp/Views/Books/_BookDetails.cshtml
@model Book

<h4>Book</h4>
<hr />
<dl class="row">
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Title)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Title)
    </dd>
    <dt class="col-sm-2">
        Authors
    </dt>
    <dd class="col-sm-10">
        <ul>
            @foreach (var bookAuthor in Model.BookAuthors)
            {
                <li><a asp-controller="Authors" asp-action="Details" asp-route-id="@bookAuthor.AuthorId">@bookAuthor.Author.FirstName @bookAuthor.Author.LastName</a></li>
            }
        </ul>
    </dd>
    <dt class="col-sm-2">
        Genres
    </dt>
    <dd class="col-sm-10">
        <ul>
            @foreach (var genre in Model.Genres)
            {
                <li><a asp-controller="Genres" asp-action="Details" asp-route-name="@genre.Genre.Name">@genre.Genre.Name</a></li>
            }
        </ul>
    </dd>
</dl>

LibraryApp/Views/Books/_BookForm.cshtml
@model EditBookViewModel

<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<input type="hidden" asp-for="Id" />
<div class="form-group">
    <label asp-for="Title" class="control-label"></label>
    <input asp-for="Title" class="form-control" />
    <span asp-validation-for="Title" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="SelectedAuthors" class="control-label"></label>
    <select multiple="multiple" asp-for="SelectedAuthors" asp-items="Model.AvailableAuthors" class="form-control"></select>
</div>
<div class="form-group">
    <label asp-for="SelectedGenres" class="control-label"></label>
    <select multiple="multiple" asp-for="SelectedGenres" asp-items="Model.AvailableGenres" class="form-control"></select>
</div>
<div class="form-group">
    <input type="submit" value="Save" class="btn btn-primary" />
</div>